### ISSUE TITLE
同时（短时间内两次）读取一个过期的数据时，会报错。

### ISSUE THREAD

**Issue by as3long** [thinkjs/think-cache-file#1]
ENOENT: no such file or drectory， unlink 'xxxxxx'

个人觉得 think-cache-file模块应该把这个错误包裹起来。返回空

**Comment by lushijie** [comment]
首先升级下依赖，如果还有问题请详细描述下具体环境和代码，暂时未复现。
另：后续提 issue 请到 https://github.com/thinkjs/thinkjs/issues，谢谢

**Comment by lushijie** [comment]
think-store-file@1.0.9 修复了此问题，请升级改模块
